---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Video capture component."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    MaxCameras: 10
    Interval: 15
    WorkingDirectory: /tmp/camera
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/VideoCapture.zip"
        Unarchive: ZIP
    Lifecycle:
      Install:
        RequiresPrivilege: true
        Script: |
          apt-get update
          apt-get install libhdf5-dev libhdf5-serial-dev libhdf5-103
          apt-get install libqt5gui5 libqt5webkit5 libqt5test5 python3-pyqt5
          apt-get install python3-dev
          pip3 install -r {artifacts:decompressedPath}/VideoCapture/requirements.txt
        Timeout: 600
      Run: 
        RequiresPrivilege: true
        Script: "python3 -u {artifacts:decompressedPath}/VideoCapture/main.py -d {configuration:/WorkingDirectory} -i {configuration:/Interval} -c {configuration:/MaxCameras}"